### ISSUE TITLE
Unsafe cast crashes with Create

### ISSUE THREAD

**Issue by TropheusJ** [Pinaz993/SimpleShelves#5]
[This line](https://github.com/Pinaz993/SimpleShelves/blob/9c16fa573b63b4a14e606d88ce894dc07858d898/src/main/java/net/pinaz993/simpleshelves/ShelfEntity.java#L133) is not safe and you should use `instanceof` instead. This causes a crash with Create: https://github.com/Fabricators-of-Create/Create/issues/643

**Comment by Pinaz993** [comment]
That is interesting. I'll make the change, but I'm curious as to why this crashes with Create, when nothing else seems to care.

**Comment by Pinaz993** [comment]
Change made in 1.17, 1.18, and master.

**Comment by Pinaz993** [comment]
Changes are live on CF.

**Comment by TropheusJ** [comment]
Thanks! This crash happens because when schematics are loaded, they [use structures](https://github.com/Fabricators-of-Create/Create/blob/f3a974148ed8432aa4bd29b70fd7bf8d3c69385d/src/main/java/com/simibubi/create/content/schematics/SchematicPrinter.java#L97) to be placed into the fake schematic world. During structure loading, the block entity will be loaded and marked as dirty, where this cast happens, causing the crash.

**Comment by Pinaz993** [comment]
The fact that structures use a subclass of World that crash on isClient()
is very strange. Very strange indeed.

**Comment by Pinaz993** [comment]
> Thanks! This crash happens because when schematics are loaded, they [use structures](https://github.com/Fabricators-of-Create/Create/blob/f3a974148ed8432aa4bd29b70fd7bf8d3c69385d/src/main/java/com/simibubi/create/content/schematics/SchematicPrinter.java#L97) to be placed into the fake schematic world. During structure loading, the block entity will be loaded and marked as dirty, where this cast happens, causing the crash.

Also, thanks for taking the time to narrow this down instead of just dumping it on me. It was really helpful and made this much quicker to fix.
