### ISSUE TITLE
[enhancement] We made Vanilla style textures. We're inviting you to use them

### ISSUE THREAD

**Issue by netcore10** [Pinaz993/SimpleShelves#6]
On my project, (an smp) we've retextured your textured books to look more vanilla ish.

We're inviting you to use them in your project if you so desire, 

![image](https://user-images.githubusercontent.com/181536/209853267-2ceba0bf-8fc9-4bd7-8dda-14edfba03c96.png)

![image](https://user-images.githubusercontent.com/181536/209853493-01753d90-8668-40d8-908e-6fd037e97e41.png)

**Comment by Pinaz993** [comment]
I'd rather not change the textures, but if you make this a project on CurseForge, I'll happily link to it there. They do look quite good, but some users are not thrilled with the bright colors. I'd rather give them the choice.
